# Generated by Django 5.1.2 on 2024-10-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
