# Generated by Django 5.1.2 on 2024-10-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_delete_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
