# Generated by Django 5.1.2 on 2024-10-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
